name: yolo_onnx_v
description: "It doesn't matter"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  onnxruntime: ^1.4.1
  camera: ^0.10.0
  permission_handler: ^12.0.0
  path_provider: ^2.0.11
  path: ^1.8.0
  image: ^4.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/yolo11n320.onnx
    - assets/models/yolo11n320nms.onnx
    - assets/models/yolov8n320.onnx
    - assets/models/yolo11n320nailsdete1229.onnx
    - assets/models/yolo11n320seg.onnx
